local ReplicatedStorage = game:GetService("ReplicatedStorage")
local DynamicTouchButton = require(ReplicatedStorage.TouchGuiButtons.DynamicTouchButton)

local SprintButton = DynamicTouchButton.new()
	:setName("Sprint")
	:setImage(9760497816)
	:setSize(90)
	:setAlign("RightTop")
	:setOrder(1)
	:setBackgroundColor(Color3.fromRGB(126, 255, 100))
	:Clicked(function(selected)
		print("Sprint clicked! Selected:", selected)
	end)
